import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const silka = localFont({
  src: "../fonts/Silka-Regular.otf",
  variable: "--font-silka",
});

const alexandria = localFont({
  src: "../fonts/Alexandria.ttf",
  variable: "--font-alexandria",
});

const clash = localFont({
  src: "../fonts/ClashDisplay-Regular.otf",
  variable: "--font-clash-display",
});

const clashBold = localFont({
  src: "../fonts/ClashDisplay-Bold.otf",
  variable: "--font-clash-display-bold",
});

export const metadata: Metadata = {
  title: "WiztecBD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${silka.variable} ${clash.variable} ${clashBold.variable} ${alexandria.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
